### ISSUE TITLE
[PoC] Create template for an API in rustlang

### ISSUE THREAD

**Issue by jmoguilevsky** [decentraland/social-service#3]
We need to create the basis of what a RUST project will look like, we need to be able to have a ready-to-go project structure with:

- [x] An HTTP server (#4)
- [x] Metrics out of the box (#5)
- [x] A metrics endpoint (#5)
- [x] Live and health endpoints (#8)
- [x] Request tracing (#10)
- [x] Have basic unit and integration tests (#12 #13)
- [x] CI Pipeline (#14)
