### ISSUE TITLE
[Query API] Setup authentication leveraging the user authentication via Matrix

### ISSUE THREAD

**Issue by jmoguilevsky** [decentraland/social-service#42]
- [x] Setup a redis instance to store the access tokens by user (#43)
- [x] Read the token in the response of the `/login` endpoint (Proxy the endpoint in the Cloudflare worker) (#44)
- [x] Define a permissions model for the endpoints (#45)
